name: Build Unity WebGL

on:
  push:
    branches:
      - main

jobs:
  buildWebGL:
    name: Build WebGL
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Cache Unity packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.unity3d
            ~/.cache/unity
          key: ${{ runner.os }}-unity

      - name: Set up Unity
        uses: game-ci/unity-setup@v2   # ✅ Use v2 to avoid the error
        with:
          unityVersion: 6000.0.42f1     # 🔁 Replace with your Unity version

      - name: Build WebGL
        uses: game-ci/unity-builder@v4
        with:
          targetPlatform: WebGL

      - name: Upload WebGL build
        uses: actions/upload-artifact@v4
        with:
          name: WebGL-Build
          path: build/WebGL
